<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Alumni;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AlumniController extends Controller
{
    /**
     * Display the alumni management page (index + create form).
     */
    public function index()
    {
        $alumniList = Alumni::orderBy('urutan')->orderBy('tahun_lulus', 'desc')->get();
        return view('admin.homepage.alumni', compact('alumniList'));
    }

    /**
     * Store a new alumni.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama'        => 'required|string|max:200',
            'instansi'    => 'required|string|max:300',
            'tahun_lulus' => 'required|integer|min:2000|max:' . (date('Y') + 1),
            'foto'        => 'nullable|image|mimes:jpg,jpeg,png,webp|max:2048',
            'urutan'      => 'nullable|integer|min:0',
        ]);

        $fotoPath = null;
        if ($request->hasFile('foto')) {
            $fotoPath = $request->file('foto')->store('alumni', 'public');
        }

        Alumni::create([
            'nama'        => $validated['nama'],
            'instansi'    => $validated['instansi'],
            'tahun_lulus' => $validated['tahun_lulus'],
            'foto'        => $fotoPath,
            'urutan'      => $validated['urutan'] ?? 0,
        ]);

        return redirect()->route('admin.alumni.index')
            ->with('success', 'Alumni "' . $validated['nama'] . '" berhasil ditambahkan.');
    }

    /**
     * Show the edit form for a specific alumni.
     *
     * NOTE: parameter MUST be named $alumnus to match the route {alumnus}
     * generated by Route::resource('alumni', ...).
     */
    public function edit(Alumni $alumnus)
    {
        $alumniList = Alumni::orderBy('urutan')->orderBy('tahun_lulus', 'desc')->get();

        // Pass to blade as 'editAlumni' to avoid collision with the $alumniList variable
        // and to keep a clear, consistent name throughout the blade template.
        return view('admin.homepage.alumni', [
            'alumniList' => $alumniList,
            'editAlumni' => $alumnus,
        ]);
    }

    /**
     * Update an existing alumni.
     *
     * NOTE: parameter MUST be named $alumnus to match the route {alumnus}.
     */
    public function update(Request $request, Alumni $alumnus)
    {
        $validated = $request->validate([
            'nama'        => 'required|string|max:200',
            'instansi'    => 'required|string|max:300',
            'tahun_lulus' => 'required|integer|min:2000|max:' . (date('Y') + 1),
            'foto'        => 'nullable|image|mimes:jpg,jpeg,png,webp|max:2048',
            'urutan'      => 'nullable|integer|min:0',
            'hapus_foto'  => 'nullable|boolean',
        ]);

        // Handle photo upload / deletion
        $fotoPath = $alumnus->foto;

        if ($request->hasFile('foto')) {
            if ($fotoPath) {
                Storage::disk('public')->delete($fotoPath);
            }
            $fotoPath = $request->file('foto')->store('alumni', 'public');
        } elseif ($request->boolean('hapus_foto')) {
            if ($fotoPath) {
                Storage::disk('public')->delete($fotoPath);
            }
            $fotoPath = null;
        }

        $alumnus->update([
            'nama'        => $validated['nama'],
            'instansi'    => $validated['instansi'],
            'tahun_lulus' => $validated['tahun_lulus'],
            'foto'        => $fotoPath,
            'urutan'      => $validated['urutan'] ?? 0,
        ]);

        return redirect()->route('admin.alumni.index')
            ->with('success', 'Alumni "' . $validated['nama'] . '" berhasil diperbarui.');
    }

    /**
     * Delete an alumni.
     *
     * NOTE: parameter MUST be named $alumnus to match the route {alumnus}.
     */
    public function destroy(Alumni $alumnus)
    {
        $nama = $alumnus->nama;
        if ($alumnus->foto) {
            Storage::disk('public')->delete($alumnus->foto);
        }
        $alumnus->delete();

        return redirect()->route('admin.alumni.index')
            ->with('success', 'Alumni "' . $nama . '" berhasil dihapus.');
    }
}
